### ISSUE TITLE
[Feature]: Alter DNS Records for Google Workspace Integration

### ISSUE THREAD

**Issue by jimbrig** [noclocks/dns#39]
- [x] Review and Remove any pre-existing `MX` records

```javascript
  , MX("@", 1, "fwd1.porkbun.com.")
  , MX("@", 1, "fwd2.porkbun.com.")
```

- [x]  Add a new `MX` record pointing to `SMTP.GOOGLE.COM`

```javascript
  , MX("@", 1, "smtp.google.com.")
```

- [x] Remove pre-existing `TXT` record for SPF

```javascript
  , TXT("@", "v=spf1 include:_spf.porkbun.com ~all")
```

- [x] Add a new `TXT` record for SPF

```javascript
  , TXT("@", "v=spf1 include:_spf.google.com ~all")
```

- [x] Review `DKIM` `TXT` record

```javascript
, TXT("default._domainkey", "v=DKIM1; k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDYsugL19bSGrFmBaj5D7mebgTI4CJbEodRIOoPetQmRGWwACeoKj3IQsI0f8Yyx8j9u6Q9IUIFJZ4TNnRP2aQHwC74O7gzA/GpNKsGHDUGPFH5f61DRj29QcmrYGTPwZPKf9zvJw4jl9vZihGJJh86zVgotMfivPQIF+8KHly3BwIDAQAB")
```  

- [x] Review any `DMARC` `TXT` records

- [x] Migrate all *email aliases* to Google as our new email hosting provider

**Comment by phoward38** [comment]
> - [ ] Migrate all email aliases to Google as our new email hosting provider

@noclocks/dev migrated aliases to my email temporarily as "alternate email addresses"; need to look into configuring forwarding in the same way.
