### ISSUE TITLE
[Feature]: Re-factor Google Workspace Email Forwarding Aliases and Routing Configuration

### ISSUE THREAD

**Issue by jimbrig** [noclocks/dns#44]
@phoward38 and @jimbrig:

Currently, @phoward38 is hoarding all of the email aliases under his user account's aliases:

![image](https://github.com/noclocks/dns/assets/32652297/ab7760b2-a4e0-4d52-ae24-c0b2c46b4ab6)

*Source: https://admin.google.com/ac/users/0haapch4c022bl/profile?action_id=ADD_ALIAS&journey=9*

Instead, we should utilize the [Email Forwarding Routing Recipients with Address Maps](https://apps.google.com/supportwidget/articlehome?hl=en&article_url=https%3A%2F%2Fsupport.google.com%2Fa%2Fanswer%2F4524505%3Fhl%3Den&assistant_id=generic-unu&product_context=4524505&product_name=UnuFlow&trigger_context=a#address-map-forwarding) functionality to enable mapping of emails to both of us.

To do this we will need to perform the following:

- [x] Remove Current Email Aliases From Patrick's User Account (except for `pat@noclocks.dev` and `patrick@noclocks.dev`):
  - [x] `admin@noclocks.dev`
  - [x] `contact@noclocks.dev`
  - [x] `feedback@noclocks.dev`
  - [x] `hello@noclocks.dev`
  - [x] `help@noclocks.dev`
  - [x] `legal@noclocks.dev`
  - [x] `news@noclocks.dev`
  - [x] `privacy@noclocks.dev`
  - [x] `sales@noclocks.dev`
  - [x] `schedule@noclocks.dev`
  - [x] `store@noclocks.dev`
  - [x] `support@noclocks.dev`
  - [x] `team@noclocks.dev`
  - [x] `test@noclocks.dev`

- [x] Add new mappings for each alias under the [Gmail app's routing > recipient address map](https://admin.google.com/ac/apps/gmail/routing) settings:
  - [x] `admin@noclocks.dev`
  - [x] `contact@noclocks.dev`
  - [x] `feedback@noclocks.dev`
  - [x] `hello@noclocks.dev`
  - [x] `help@noclocks.dev`
  - [x] `legal@noclocks.dev`
  - [x] `news@noclocks.dev`
  - [x] `privacy@noclocks.dev`
  - [x] `sales@noclocks.dev`
  - [x] `schedule@noclocks.dev`
  - [x] `store@noclocks.dev`
  - [x] `support@noclocks.dev`
  - [x] `team@noclocks.dev`
  - [x] `test@noclocks.dev`

To automate this, you can *bulk add* aliases all at once.

Screenshots:

![image](https://github.com/noclocks/dns/assets/32652297/a75bce6f-d630-40aa-9fe0-fd45cb3b9a1e)

![image](https://github.com/noclocks/dns/assets/32652297/8f8bddd4-bd3c-4e71-a2cc-0642c2235c04)

![image](https://github.com/noclocks/dns/assets/32652297/75727c48-c88f-4437-b2df-bda090ead9d2)

![image](https://github.com/noclocks/dns/assets/32652297/8e37ed2c-601e-4169-8814-15c7c2d50644)

**Comment by jimbrig** [comment]
Sent Test Email to all aliases from my personal email: jimmy.briggs@jimbrig.com to see if working:

![image](https://github.com/noclocks/dns/assets/32652297/37582634-2d7d-4044-a786-c19e778afab3)

**Comment by phoward38** [comment]
> Sent Test Email to all aliases from my personal email: jimmy.briggs@jimbrig.com to see if working:
> 
> 
> 
> ![image](https://github.com/noclocks/dns/assets/32652297/37582634-2d7d-4044-a786-c19e778afab3)
> 
> 

@noclocks/dev for records, worked for me after update

**Comment by jimbrig** [comment]
Think this is good to go now - also just verified our GitHub Email again `dev@noclocks.dev` (got un-verified due to this stuff and I couldn't verify without fixing this first): 

![image](https://github.com/noclocks/dns/assets/32652297/fce45adf-4dd8-4d88-bd5d-51406d51f968)
